name: CI
on:
  push:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Retrive Next.js cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Build
        run: yarn build
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

  code_style:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: prettier
        run: yarn prettier

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: eslint
        run: yarn lint

  tests:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Clone backend
        uses: actions/checkout@v2
        with:
          repository: boklisten/bl-api
          path: "./bl-api"
      - name: Start backend
        run: |
          cd bl-api
          yarn install --frozen-lockfile --production
          yarn start &
        env:
          PORT: 1337
          BLAPI_HOST: localhost
          BLAPI_PORT: 1337
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SERVER_PATH: /
          NODE_ENV: dev
          LOG_LEVEL: silly
          URI_WHITELIST: localhost:3000 http://localhost:3000
          ACCESS_TOKEN_SECRET: not_secret_at_all
          BL_API_URI: http://localhost:1337/
          CLIENT_URI: http://localhost:3000/
          REFRESH_TOKEN_SECRET: not_the_prod_secret
          DIBS_CHECKOUT_KEY: ${{ secrets.DIBS_CHECKOUT_KEY }}
          DIBS_SECRET_KEY: ${{ secrets.DIBS_CHECKOUT_SECRET }}
          DIBS_URI: https://test.api.dibspayment.eu/v1/
          FACEBOOK_CLIENT_ID: 123
          FACEBOOK_SECRET: 123
          FEIDE_AUTHORIZATION_URL: https://auth.dataporten.no/oauth/authorization
          FEIDE_CLIENT_ID: yello
          FEIDE_SECRET: foo
          FEIDE_TOKEN_URL: https://auth.dataporten.no/oauth/token
          FEIDE_USER_INFO_URL: https://auth.dataporten.no/userinfo
          GOOGLE_CLIENT_ID: totally_legit
          GOOGLE_SECRET: nope
          SENDGRID_API_KEY: foo
          TWILIO_SMS_AUTH_TOKEN: foo
          TWILIO_SMS_SID: foo
          TWILIO_STATUS_CALLBACK_URL: foo
          BRING_API_KEY: ${{ secrets.BRING_API_KEY }}
          BRING_API_ID: ${{ secrets.BRING_API_ID }}
      - name: Install Cypress
        run: yarn cypress install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn start
          record: true
          parallel: true
          group: "UI - Electron"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          BRING_API_KEY: ${{ secrets.BRING_API_KEY }}
          BRING_API_ID: ${{ secrets.BRING_API_ID }}
